[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']
home=['<Super>h']
www=['<Super>b']

[custom-keybindings/custom0]
binding='<Super>Return'
command='kitty'
name='kitty terminal'

[custom-keybindings/custom1]
binding=''
command='ibus engine ibus-avro'
name='to bangla'

[custom-keybindings/custom2]
binding='<Shift><Super>space'
command='ibus engine xkb:us::eng'
name='to english'
